//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinVerCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinVerCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Database file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageDatabaseNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextClean {
            get {
                return ResourceManager.GetString("HelpTextClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output collected windows version info. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextOutput {
            get {
                return ResourceManager.GetString("HelpTextOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not display processing results. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextQuiet {
            get {
                return ResourceManager.GetString("HelpTextQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display collected windows version info. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextShow {
            get {
                return ResourceManager.GetString("HelpTextShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display windows version info. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpTextVerbose {
            get {
                return ResourceManager.GetString("HelpTextVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageComplete {
            get {
                return ResourceManager.GetString("MessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create database file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCreateDatabase {
            get {
                return ResourceManager.GetString("MessageCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now cleaning... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNowCleaning {
            get {
                return ResourceManager.GetString("MessageNowCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now collecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNowCollecting {
            get {
                return ResourceManager.GetString("MessageNowCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now outputting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNowOutputting {
            get {
                return ResourceManager.GetString("MessageNowOutputting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter any key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePause {
            get {
                return ResourceManager.GetString("MessagePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thank you for cooperation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageThanks {
            get {
                return ResourceManager.GetString("MessageThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HostName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringHostName {
            get {
                return ResourceManager.GetString("StringHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastUpdate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLastUpdate {
            get {
                return ResourceManager.GetString("StringLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringProductName {
            get {
                return ResourceManager.GetString("StringProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringUnknown {
            get {
                return ResourceManager.GetString("StringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringUserName {
            get {
                return ResourceManager.GetString("StringUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringVersion {
            get {
                return ResourceManager.GetString("StringVersion", resourceCulture);
            }
        }
    }
}
